version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: xcv
    main: ./cmd/xcv
    binary: xcv
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: xcv
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

nix:
  - name: xcv
    ids: [xcv]
    homepage: "https://github.com/rwilgaard/xcv"
    description: "CLI tool for inspecting, validating, and comparing X.509 certificate chains"
    license: "mit"
    main_program: "xcv"
    dependencies:
      - name: installShellFiles
    post_install: |
      installShellCompletion --cmd xcv \
        --zsh <($out/bin/xcv completion zsh) \
        --bash <($out/bin/xcv completion bash) \
        --fish <($out/bin/xcv completion fish)
    repository:
      owner: rwilgaard
      name: nix-packages
      branch: main
      token: "{{ .Env.NIX_PACKAGES_TOKEN }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
